name = "checklist"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
modem = ">= 2.0.0 and < 3.0.0"
rada = ">= 0.5.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.0.0 and < 3.0.0"

[tools.lustre.html]
stylesheets = [
  { href = "/static/output.css" }
]
